# This workflow will build ccu-jack

name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.x'

    - name: Build
      run: |
        cd build
        go run .

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        path: |
          ccu-jack-*.tar.gz
          ccu-jack-*.zip
        name: ccu-jack-${{ github.sha }}
        retention-days: 30
